### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by naiiytom** [xellows1305/Scene-Text-Rectification#2]
Dear Author,

Thank you for your hard working.
If it's not much of a request.
Could you please open source the code?

Thank you in regards.

**Comment by taeho-kil** [comment]
Sorry, the source code for this algorithm can not be opened. 
Best regard,

**Comment by bowen-upenn** [comment]
Hello!! Will you consider releasing the project as either a commercial or free software product so that we can run the inference? This will help our research a lot. Thanks.
